site_name: :package_name
site_description: :package_description
site_url: https://:vendor_slug.github.io/:package_slug
repo_url: https://github.com/:vendor_slug/:package_slug
repo_name: :vendor_slug/:package_slug

theme:
  # Customize Material for MkDocs: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Testing: testing.md
